name: future_life
description: "Life Simulator - See where your daily habits will take you."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^14.6.2

  # Charts
  fl_chart: ^0.69.0

  # Internationalization
  intl: ^0.20.2

  # Animations
  flutter_animate: ^4.5.0

  # Typography
  google_fonts: ^6.2.1

  # Unique IDs
  uuid: ^4.4.2
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.4
  google_nav_bar: ^5.0.7

  # Network
  dio: ^5.7.0
  retrofit: ^4.4.1
  logger: ^2.4.0
  flutter_secure_storage: ^9.2.2

  # Google Sign-In
  google_sign_in: ^6.2.1
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf

    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher_icon/icon.png"
  adaptive_icon_background: "#0A0B10"
  adaptive_icon_foreground: "assets/launcher_icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/launcher_icon/icon.png"

flutter_native_splash:
  color: "#0A0B10" # AppColors.background equivalent
  image: "assets/launcher_icon/splash.png"
  android_12:
    image: "assets/launcher_icon/splash.png"
    icon_background_color: "#0A0B10"
  android: true
  ios: true
  web: false
